# This is a basic workflow to help you get started with Actions

name: Test Firebase rules and callable functions on PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_firestore_security_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checking-out
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Installing Firebase CLI
        run: npm install -g firebase-tools

      - name: Installing npm dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Running unit tests
        run: firebase emulators:exec --only firestore 'npm run test'
